heat_template_version: 2015-10-15

description: >

parameters:
                   #                                            #
                   #                                            #
                   #           P A R A M E T E R E S            #
                   #                                            #
                   #                                            #

# NETWORK
 private_network_subnet:
  type: string
  description: ID of public network for which floating IP addresses will be allocated
  default: "192.168.2.0/24"

 private_network_dns_server:
  type: string
  description: Private network dns
  default: ["8.8.8.8", "4.2.2.4"]

# INSTANCES

 key_name:
  type: string
  description: Pair key name
  default: cs-datacaching

 swarm_keyvaluestore_flv:
  type: string
  description: flavor for swarm key value store host
  default: kvm.m1.small


 swarm_manager_flv:
  type: string
  description: flavor for swarm manager host
  default: kvm.m1.small

 swarm_workers_flv:
  type: string
  description: flavor for swarm worker hosts
  default : kvm.m2.medium

 image_id:
  type: string
  description: image which would use for nodes
  default: e9cf0016-07c1-43e6-ac8a-8a034f0e7755

 private_subnet_id:
  type: string
  description: ID of private sub network into which servers get deployed
  default: 7c1650ef-5227-4917-9990-0a1de98cd506

 number_of_node:
  type: string
  description: number of client node which would join to the cluster
  default: 2


                   #                                            #
                   #                                            #
                   #           R E S O U R C E S                #
                   #                                            #
                   #                                            #

resources:

 internal_net:
  type: OS::Neutron::Net

 internal_subnet:
  type: OS::Neutron::Subnet
  properties:
   network_id: { get_resource: internal_net }
   cidr: { get_param: private_network_subnet }
   dns_nameservers: {get_param: private_network_dns_server}
   ip_version: 4

 internal_router:
  type: OS::Neutron::Router
  properties:
   external_gateway_info: { network: public }

 internal_interface:
  type: OS::Neutron::RouterInterface
  properties:
   router_id: { get_resource: internal_router }
   subnet: { get_resource: internal_subnet }

 keyValue_config_wait_handle:
  type: AWS::CloudFormation::WaitConditionHandle

 keyValue_config_wait_condition:
  type: AWS::CloudFormation::WaitCondition
  properties:
   Handle:
    get_resource: keyValue_config_wait_handle
   Timeout: 1000

 manager_config_wait_handle:
  type: AWS::CloudFormation::WaitConditionHandle

 manager_config_wait_condition:
  type: AWS::CloudFormation::WaitCondition
  properties:
   Handle:
    get_resource: manager_config_wait_handle
   Timeout: 1000


 node_wait_handle:
  type: AWS::CloudFormation::WaitConditionHandle

 node_wait_condition:
  type: AWS::CloudFormation::WaitCondition
  depends_on: Clients
  properties:
   Handle:
    get_resource: node_wait_handle
   Timeout: 1000


 heat_param:
  type: OS::Heat::SoftwareConfig
  properties:
   group: system
   config:
    str_replace:
     template: { get_file: resource_deployment/heat_asset/heat_param.yaml }
     params:
      $WAIT_HANDLE: {get_resource: node_wait_handle }

 enable_login:
  type: OS::Heat::SoftwareConfig
  properties:
   group: system
   config:
    str_replace:
     template: { get_file: resource_deployment/heat_asset/enable_login.yaml }
     params:
      $empty: ""


 cfn_signal:
  type: OS::Heat::SoftwareConfig
  properties:
   group: ungrouped
   config: {get_file: resource_deployment/heat_asset/signal.sh}

 keyvalue_config:
  type: OS::Heat::SoftwareConfig
  properties:
   group: ungrouped
   config:
    str_replace:
     template: {get_file: resource_deployment/heat_asset/docker_setup.sh}
     params:
      $role: "keystore"

 manager_config:
  type: OS::Heat::SoftwareConfig
  properties:
   group: ungrouped
   config:
    str_replace:
     template: {get_file: resource_deployment/heat_asset/docker_setup.sh}
     params:
      $role: "manager"

      $keyValue: "192.168.2.10"


 client_config:
  type: OS::Heat::SoftwareConfig
  properties:
   group: ungrouped
   config:
    str_replace:
     template: {get_file: resource_deployment/heat_asset/docker_setup.sh}
     params:
      $role: "client"
      $keyValue: "192.168.2.10"

 keyvalue_node_init:
  type: OS::Heat::MultipartMime
  properties:
    parts:
     - config: { get_resource: enable_login }

     - config: { get_resource: keyvalue_config }
     - config:
         str_replace:
           template: |
            #!/bin/bash -v
            curl -sf -X PUT -H 'Content-Type: application/json' \
            --data-binary '{"Status": "SUCCESS","Reason": "Key Value Setup completed","Data": "OK", "UniqueId": "00001"}' \
            "$WAIT_HANDLE"
           params:
             $WAIT_HANDLE: {get_resource: keyValue_config_wait_handle }

 manager_node_init:
  type: OS::Heat::MultipartMime
  properties:
    parts:
     # - config: { get_resource: docker_src }
     - config: { get_resource: manager_config }
     - config:
         str_replace:
           template: |
            #!/bin/bash -v
            curl -sf -X PUT -H 'Content-Type: application/json' \
            --data-binary '{"Status": "SUCCESS","Reason": "Manager Setup completed","Data": "OK", "UniqueId": "00002"}' \
            "$WAIT_HANDLE"
           params:
             $WAIT_HANDLE: {get_resource: manager_config_wait_handle }

 client_node_init:
  type: OS::Heat::MultipartMime
  properties:
    parts:
     - config: { get_resource: enable_login }
     - config: { get_resource: heat_param }
     - config: { get_resource: client_config }
     - config: { get_resource: cfn_signal }


 KeyValue:
  type: OS::Nova::Server
  properties:
   image: { get_param: image_id }
   flavor: { get_param: swarm_keyvaluestore_flv }
   key_name: { get_param: key_name }
   networks:
     - port: { get_resource: KeyValue_port }
   user_data_format: RAW
   user_data: { get_resource: keyvalue_node_init  }


 Manager:
  type: OS::Nova::Server
  properties:
   image: { get_param: image_id }
   flavor: { get_param: swarm_manager_flv }
   key_name: { get_param: key_name }
   networks:
     - port: { get_resource: manager_port }
   user_data_format: RAW
   user_data: { get_resource: manager_node_init  }

 Clients:
  type: OS::Heat::ResourceGroup
  properties:
   count: { get_param: number_of_node }
   resource_def:
    type: OS::Nova::Server
    properties:
     image: { get_param: image_id }
     flavor: { get_param: swarm_workers_flv }
     key_name: { get_param: key_name }
     networks:
       - network: {get_resource: internal_net}
     user_data_format: RAW
     user_data: { get_resource: client_node_init  }

 KeyValue_port:
    type: OS::Neutron::Port
    properties:
        name: "keyValue_port"
        network_id: { get_resource: internal_net }
        fixed_ips:
            - subnet_id: { get_resource: internal_subnet }
              ip_address: 192.168.2.10

 manager_port:
  type: OS::Neutron::Port
  properties:
   name: "manager_port"
   network_id: { get_resource: internal_net }
   fixed_ips:
       - subnet_id: { get_resource: internal_subnet }

 manager_floating_ip:
  type: OS::Neutron::FloatingIP
  properties:
   floating_network_id: public
   port_id: { get_resource: manager_port }

                   #                                            #
                   #                                            #
                   #       T E M P L A T E   O U T P U T        #
                   #                                            #
                   #                                            #

outputs:

 Manager_Public_ip:
  value: { get_attr: [manager_floating_ip, floating_ip_address] }